# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
    #step 1 
  build1:
    runs-on: ubuntu-latest
    steps:       
      - uses: JimCronqvist/action-ssh@master
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
    #step 2      

      # Runs a single command using the runners shell
  build2: 
    runs-on: ubuntu-latest
    steps: 
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          privateKey: ${{ secrets.UBUNT_GEP }}
      - name: Docker running   
        run: docker ps -a
  stop action:
    runs-on: ubuntu-latest
    steps:
      - name: Stop workflow
        needs: [build,build1,build2]
        if: build == completed
        run:
            build2

      # step 3  

   
        

      
       
       
       
